Added `ankestachelt`
ahaeslich/ankelegt pull request #21
Opened 2024-10-23 16:53 UTC by Jan3k3y

2024-10-23 16:57 UTC, ahaeslich requested changes

2024-10-23 16:57 UTC, ahaeslich commented on list/list.json
> +      "description": "wenn es alle machen, fühlt man sich dazu..."
Hast du noch einen richtigen Social-Media-Kanalnamen für mich?

2024-10-23 16:59 UTC, Jan3k3y commented on list/list.json
> +      "description": "wenn es alle machen, fühlt man sich dazu..."
Na klar

2025-05-21 09:55 UTC, christophervoigt approved these changes

2025-05-21 09:56 UTC, christophervoigt commented on list/list.json
> +      "description": "wenn es alle machen, fühlt man sich dazu..."
Bienenkanal find ich gut

2025-05-21 09:56 UTC, christophervoigt commented
@Jan3k3y du musst nur bitte nochmal Konflikte auflösen

2025-06-24 10:54 UTC, ahaeslich approved these changes

2025-06-24 10:56 UTC, merged